//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1573, 1591

using System;
using System.Linq;

using LinqToDB;
using LinqToDB.Configuration;
using LinqToDB.Mapping;

namespace DataModels
{
	/// <summary>
	/// Database       : saasdb
	/// Data Source    : saas.pbmscore.com
	/// Server Version : 8.0.29-0ubuntu0.20.04.3
	/// </summary>
	public partial class SaasdbDB : LinqToDB.Data.DataConnection
	{
		public ITable<TblCompany>          TblCompanies         { get { return this.GetTable<TblCompany>(); } }
		public ITable<TblCustomer>         TblCustomers         { get { return this.GetTable<TblCustomer>(); } }
		public ITable<TblPbm>              TblPbms              { get { return this.GetTable<TblPbm>(); } }
		public ITable<TblTicketPermission> TblTicketPermissions { get { return this.GetTable<TblTicketPermission>(); } }
		public ITable<TblToDo>             TblToDoes            { get { return this.GetTable<TblToDo>(); } }
		public ITable<TblToDoDetail>       TblToDoDetails       { get { return this.GetTable<TblToDoDetail>(); } }
		public ITable<TblUser>             TblUsers             { get { return this.GetTable<TblUser>(); } }

		public SaasdbDB()
		{
			InitDataContext();
			InitMappingSchema();
		}

		public SaasdbDB(string configuration)
			: base(configuration)
		{
			InitDataContext();
			InitMappingSchema();
		}

		public SaasdbDB(LinqToDBConnectionOptions options)
			: base(options)
		{
			InitDataContext();
			InitMappingSchema();
		}

		public SaasdbDB(LinqToDBConnectionOptions<SaasdbDB> options)
			: base(options)
		{
			InitDataContext();
			InitMappingSchema();
		}

		partial void InitDataContext  ();
		partial void InitMappingSchema();
	}

	[Table("tbl_Company")]
	public partial class TblCompany
	{
		[Column("companyId"),          PrimaryKey,  NotNull] public decimal   CompanyId          { get; set; } // decimal(18,0)
		[Column("companyName"),           Nullable         ] public string    CompanyName        { get; set; } // longtext
		[Column("companyNameAr"),         Nullable         ] public string    CompanyNameAr      { get; set; } // longtext
		[Column("mailingName"),           Nullable         ] public string    MailingName        { get; set; } // longtext
		[Column("address"),               Nullable         ] public string    Address            { get; set; } // longtext
		[Column("phone"),                 Nullable         ] public string    Phone              { get; set; } // longtext
		[Column("mobile"),                Nullable         ] public string    Mobile             { get; set; } // longtext
		[Column("emailId"),               Nullable         ] public string    EmailId            { get; set; } // longtext
		[Column("web"),                   Nullable         ] public string    Web                { get; set; } // longtext
		[Column("country"),               Nullable         ] public string    Country            { get; set; } // longtext
		[Column("state"),                 Nullable         ] public string    State              { get; set; } // longtext
		[Column("pin"),                   Nullable         ] public string    Pin                { get; set; } // longtext
		[Column("currencyId"),            Nullable         ] public decimal?  CurrencyId         { get; set; } // decimal(18,0)
		[Column("financialYearFrom"),     Nullable         ] public DateTime? FinancialYearFrom  { get; set; } // datetime
		[Column("booksBeginingFrom"),     Nullable         ] public DateTime? BooksBeginingFrom  { get; set; } // datetime
		[Column("tin"),                   Nullable         ] public string    Tin                { get; set; } // longtext
		[Column("cst"),                   Nullable         ] public string    Cst                { get; set; } // longtext
		[Column("pan"),                   Nullable         ] public string    Pan                { get; set; } // longtext
		[Column("currentDate"),           Nullable         ] public DateTime? CurrentDate        { get; set; } // datetime
		[Column("logo"),                  Nullable         ] public byte[]    Logo               { get; set; } // longblob
		[Column("extra1"),                Nullable         ] public string    Extra1             { get; set; } // longtext
		[Column("extra2"),                Nullable         ] public string    Extra2             { get; set; } // longtext
		[Column("extraDate"),             Nullable         ] public DateTime? ExtraDate          { get; set; } // datetime
		[Column("ct"),                    Nullable         ] public string    Ct                 { get; set; } // longtext
		[Column("fax"),                   Nullable         ] public string    Fax                { get; set; } // longtext
		[Column("addressAr"),             Nullable         ] public string    AddressAr          { get; set; } // longtext
		[Column("stateAr"),               Nullable         ] public string    StateAr            { get; set; } // longtext
		[Column("countryAr"),             Nullable         ] public string    CountryAr          { get; set; } // longtext
		[Column("compnayWorkingMode"),    Nullable         ] public string    CompnayWorkingMode { get; set; } // varchar(50)
	}

	[Table("tbl_Customer")]
	public partial class TblCustomer
	{
		[Column("customerId"),           PrimaryKey,  NotNull] public decimal   CustomerId           { get; set; } // decimal(18,0)
		[Column("customerName"),            Nullable         ] public string    CustomerName         { get; set; } // longtext
		[Column("customerNameAr"),          Nullable         ] public string    CustomerNameAr       { get; set; } // longtext
		[Column("mobile"),                  Nullable         ] public string    Mobile               { get; set; } // longtext
		[Column("address"),                 Nullable         ] public string    Address              { get; set; } // longtext
		[Column("email"),                   Nullable         ] public string    Email                { get; set; } // longtext
		[Column("routId"),                  Nullable         ] public decimal?  RoutId               { get; set; } // decimal(18,0)
		[Column("joinDate"),                Nullable         ] public DateTime? JoinDate             { get; set; } // date
		[Column("branchId"),                Nullable         ] public decimal?  BranchId             { get; set; } // decimal(18,0)
		[Column("insuranceCompany"),        Nullable         ] public decimal?  InsuranceCompany     { get; set; } // decimal(18,0)
		[Column("policyNo"),                Nullable         ] public decimal?  PolicyNo             { get; set; } // decimal(18,0)
		[Column("insuranceClass"),          Nullable         ] public string    InsuranceClass       { get; set; } // longtext
		[Column("extra1"),                  Nullable         ] public string    Extra1               { get; set; } // longtext
		[Column("extra2"),                  Nullable         ] public string    Extra2               { get; set; } // longtext
		[Column("pointsOpeningBalance"),    Nullable         ] public decimal?  PointsOpeningBalance { get; set; } // decimal(18,0)
		[Column("isLoyalty"),               Nullable         ] public sbyte?    IsLoyalty            { get; set; } // tinyint
		[Column("pointsGainRate"),          Nullable         ] public decimal?  PointsGainRate       { get; set; } // decimal(10,2)
		[Column("pointsExchangeRate"),      Nullable         ] public decimal?  PointsExchangeRate   { get; set; } // decimal(10,2)
		[Column("lastLoyaltyUpgrade"),      Nullable         ] public DateTime? LastLoyaltyUpgrade   { get; set; } // date
		[Column("loyaltyLevelId"),          Nullable         ] public int?      LoyaltyLevelId       { get; set; } // int
		[Column("loyaltyGroupId"),          Nullable         ] public decimal?  LoyaltyGroupId       { get; set; } // decimal(18,0)
		[Column("loyaltyCardNo"),           Nullable         ] public string    LoyaltyCardNo        { get; set; } // longtext
		[Column("userId"),                  Nullable         ] public decimal?  UserId               { get; set; } // decimal(18,0)
		[Column("payType"),                 Nullable         ] public string    PayType              { get; set; } // varchar(50)
		[Column("phone"),                   Nullable         ] public string    Phone                { get; set; } // varchar(50)
		[Column("partyType"),               Nullable         ] public string    PartyType            { get; set; } // varchar(50)
		[Column("ledgerId"),                Nullable         ] public decimal?  LedgerId             { get; set; } // decimal(18,0)
	}

	[Table("tbl_PBMS")]
	public partial class TblPbm
	{
		[Column("id"),    PrimaryKey,  NotNull] public int    Id    { get; set; } // int
		[Column("col1"),     Nullable         ] public string Col1  { get; set; } // longtext
		[Column("col2"),     Nullable         ] public string Col2  { get; set; } // longtext
		[Column("col3"),     Nullable         ] public string Col3  { get; set; } // longtext
		[Column("col4"),     Nullable         ] public string Col4  { get; set; } // longtext
		[Column("col5"),     Nullable         ] public string Col5  { get; set; } // longtext
		[Column("col6"),     Nullable         ] public string Col6  { get; set; } // longtext
		[Column("col7"),     Nullable         ] public string Col7  { get; set; } // longtext
		[Column("col8"),     Nullable         ] public string Col8  { get; set; } // longtext
		[Column("col9"),     Nullable         ] public string Col9  { get; set; } // longtext
		[Column("col10"),    Nullable         ] public string Col10 { get; set; } // longtext
		[Column("col11"),    Nullable         ] public string Col11 { get; set; } // longtext
		[Column("col12"),    Nullable         ] public string Col12 { get; set; } // longtext
		[Column("col13"),    Nullable         ] public string Col13 { get; set; } // longtext
		[Column("col14"),    Nullable         ] public string Col14 { get; set; } // longtext
		[Column("col15"),    Nullable         ] public string Col15 { get; set; } // longtext
		[Column("col16"),    Nullable         ] public string Col16 { get; set; } // longtext
		[Column("col17"),    Nullable         ] public string Col17 { get; set; } // longtext
		[Column("col18"),    Nullable         ] public string Col18 { get; set; } // longtext
		[Column("col19"),    Nullable         ] public string Col19 { get; set; } // longtext
		[Column("col20"),    Nullable         ] public string Col20 { get; set; } // longtext
		[Column("col21"),    Nullable         ] public string Col21 { get; set; } // longtext
		[Column("col22"),    Nullable         ] public string Col22 { get; set; } // longtext
	}

	[Table("tbl_TicketPermission")]
	public partial class TblTicketPermission
	{
		[Column("id"),         PrimaryKey,  NotNull] public int       Id         { get; set; } // int
		[Column("formName"),      Nullable         ] public string    FormName   { get; set; } // varchar(255)
		[Column("actionName"),    Nullable         ] public string    ActionName { get; set; } // varchar(255)
		[Column("userId"),        Nullable         ] public int?      UserId     { get; set; } // int
		[Column("canCreate"),     Nullable         ] public string    CanCreate  { get; set; } // varchar(255)
		[Column("canRead"),       Nullable         ] public string    CanRead    { get; set; } // varchar(255)
		[Column("canUpdate"),     Nullable         ] public DateTime? CanUpdate  { get; set; } // datetime
		[Column("canDelete"),     Nullable         ] public string    CanDelete  { get; set; } // varchar(255)
	}

	[Table("tbl_ToDo")]
	public partial class TblToDo
	{
		[Column("id"),            PrimaryKey, Identity] public int       Id            { get; set; } // int
		[Column("toDoSubject"),   Nullable            ] public string    ToDoSubject   { get; set; } // longtext
		[Column("teamMember"),    Nullable            ] public string    TeamMember    { get; set; } // varchar(255)
		[Column("creationDate"),  Nullable            ] public DateTime? CreationDate  { get; set; } // datetime
		[Column("lastStatus"),    Nullable            ] public string    LastStatus    { get; set; } // varchar(255)
		[Column("companyId"),     Nullable            ] public decimal?  CompanyId     { get; set; } // decimal(10,0)
		[Column("imageFileName"), Nullable            ] public string    ImageFileName { get; set; } // varchar(255)
		[Column("lastUpdate"),    Nullable            ] public DateTime? LastUpdate    { get; set; } // datetime
	}

	[Table("tbl_ToDoDetails")]
	public partial class TblToDoDetail
	{
		[Column("id"),         PrimaryKey, Identity] public int       Id         { get; set; } // int
		[Column("toDoId"),     Nullable            ] public int?      ToDoId     { get; set; } // int
		[Column("slno"),       Nullable            ] public int?      Slno       { get; set; } // int
		[Column("teamMember"), Nullable            ] public string    TeamMember { get; set; } // varchar(255)
		[Column("notes"),      Nullable            ] public string    Notes      { get; set; } // longtext
		[Column("extraDate"),  Nullable            ] public DateTime? ExtraDate  { get; set; } // datetime
	}

	[Table("tbl_User")]
	public partial class TblUser
	{
		[Column("userId"),        PrimaryKey(1), NotNull] public decimal   UserId        { get; set; } // decimal(18,0)
		[Column("userName"),         Nullable           ] public string    UserName      { get; set; } // longtext
		[Column("password"),         Nullable           ] public string    Password      { get; set; } // longtext
		[Column("active"),           Nullable           ] public sbyte?    Active        { get; set; } // tinyint
		[Column("roleId"),           Nullable           ] public decimal?  RoleId        { get; set; } // decimal(18,0)
		[Column("narration"),        Nullable           ] public string    Narration     { get; set; } // longtext
		[Column("extraDate"),        Nullable           ] public DateTime? ExtraDate     { get; set; } // datetime
		[Column("extra1"),           Nullable           ] public string    Extra1        { get; set; } // longtext
		[Column("extra2"),           Nullable           ] public string    Extra2        { get; set; } // longtext
		[Column("employeeId"),       Nullable           ] public decimal?  EmployeeId    { get; set; } // decimal(18,0)
		[Column("companyId"),     PrimaryKey(2), NotNull] public decimal   CompanyId     { get; set; } // decimal(18,0)
		[Column("apiKey"),           Nullable           ] public string    ApiKey        { get; set; } // varchar(150)
		[Column("apiExpiryDate"),    Nullable           ] public DateTime? ApiExpiryDate { get; set; } // datetime
	}

	public static partial class TableExtensions
	{
		public static TblCompany Find(this ITable<TblCompany> table, decimal CompanyId)
		{
			return table.FirstOrDefault(t =>
				t.CompanyId == CompanyId);
		}

		public static TblCustomer Find(this ITable<TblCustomer> table, decimal CustomerId)
		{
			return table.FirstOrDefault(t =>
				t.CustomerId == CustomerId);
		}

		public static TblPbm Find(this ITable<TblPbm> table, int Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static TblTicketPermission Find(this ITable<TblTicketPermission> table, int Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static TblToDo Find(this ITable<TblToDo> table, int Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static TblToDoDetail Find(this ITable<TblToDoDetail> table, int Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static TblUser Find(this ITable<TblUser> table, decimal UserId, decimal CompanyId)
		{
			return table.FirstOrDefault(t =>
				t.UserId    == UserId &&
				t.CompanyId == CompanyId);
		}
	}
}
